spring.application.name=smartfarmerbackendai
server.port=8081

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:smartfarmerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# CORS
spring.web.cors.allowed-origins=http://localhost:3000

# JWT
jwt.secret=smartfarmersecretkey123456789
jwt.expiration=86400000
groq.api.key=gsk
weather.api.key=f